package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BuildTest'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BuildTest")) {
    params {
        add {
            password("secretPAram", "credentialsJSON:485166ba-6bb0-4a15-bb35-2c0ea231858c", label = "secretLabel", description = "SecretDesc", display = ParameterDisplay.HIDDEN, readOnly = true)
        }
        add {
            param("super_param", "testValue")
        }
    }
}
